services:
  frontend: #our service name
    image: saitbutun/frontend:latest 
    ports:
      - 3000:3000
    stdin_open: true #keeps the standart input open
    volumes:
      - ./frontend:/usr/src/app 
      - /usr/src/app/node_modules
    restart: always #if containers stop or crahsed Docker will automaticly restart it
    networks:
      - react-express #this network connect frontend and backend container
    depends_on:
      - backend #do not start before backend container

  backend:
    restart: always
    image: saitbutun/backend:latest
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose: 
      - 3000
  mongo:
    restart: always
    image: mongo:4.2.0 #it will pull up from dockerhub
    volumes:
      - ./data:/data/db # to keep data with no lose 
    networks:
      - express-mongo
    expose:
      - 27017
networks:
  react-express:
  express-mongo:
