name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repomuza gecme isi
      uses: actions/checkout@v4

    - name: Dockerhuba loglama isi
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker backend image build etme isi
      run: |
        cd ./react-express-mongodb/
        docker build -t saitbutun/backend:latest ./backend
        docker push saitbutun/backend:latest
    - name: Docker frontend image build etme isi
      run: |
        cd ./react-express-mongodb/
        docker build -t saitbutun/frontend:latest ./frontend
        docker push saitbutun/frontend:latest
        
